import * as Constants from '../constants/constants'

export default [
  {
    name: 'name',
    label: 'Name',
    placeholder: 'Enter a name',
    type: Constants.TEXT_INPUT,
    value: '',
    state: Constants.ENABLED,
    style: '',
    onChange: undefined,
    onClick: undefined,
  },
  {
    name: 'name',
    label: 'Name',
    placeholder: 'enter a name...',
    type: Constants.TEXT_INPUT,
    value: '',
    state: Constants.ENABLED,
    style: '',
    onChange: undefined,
    onClick: undefined,
  },
  {
    name: 'company',
    label: 'Company',
    placeholder: 'enter your company name...',
    type: Constants.TEXT_INPUT,
    value: '',
    state: Constants.ENABLED,
    style: '',
    onChange: undefined,
    onClick: undefined,
  },
  {
    name: 'website',
    label: 'Website',
    placeholder: 'enter your company website...',
    type: Constants.TEXT_INPUT,
    value: '',
    state: Constants.ENABLED,
    style: '',
    onChange: undefined,
    onClick: undefined,
  },
  {
    name: 'specialty',
    label: 'specialty',
    placeholder: 'Enter your candy name...',
    type: Constants.TEXT_INPUT,
    value: '',
    state: Constants.ENABLED,
    style: '',
    onChange: undefined,
    onClick: undefined,
  },
  {
    name: 'price',
    label: 'price',
    placeholder: 'Enter a suggested price...',
    type: Constants.TEXT_INPUT,
    value: '',
    state: Constants.ENABLED,
    style: '',
    onChange: undefined,
    onClick: undefined,
  },
]
