import * as Constants from '../constants/constants'
import TextInput from '../components/TextInput'

export default [
  {
    name: 'name',
    label: 'name:',
    placeholder: 'enter your name...',
    FormComponent: TextInput,
    value: '',
    state: Constants.ENABLED,
    style: '',
    onChange: undefined,
    onClick: undefined,
  },
  {
    name: 'company',
    label: 'company:',
    placeholder: 'enter your company name...',
    FormComponent: TextInput,
    value: '',
    state: Constants.ENABLED,
    style: '',
    onChange: undefined,
    onClick: undefined,
  },
  {
    name: 'website',
    label: 'website:',
    placeholder: 'enter your company website...',
    FormComponent: TextInput,
    value: '',
    state: Constants.ENABLED,
    style: '',
    onChange: undefined,
    onClick: undefined,
  },
  {
    name: 'email',
    label: 'email address:',
    placeholder: 'enter your email address...',
    FormComponent: TextInput,
    value: '',
    state: Constants.ENABLED,
    style: '',
    onChange: undefined,
    onClick: undefined,
  },
  {
    name: 'specialty',
    label: 'top candy specialty (enter only one):',
    placeholder: 'enter a candy name...',
    FormComponent: TextInput,
    value: '',
    state: Constants.ENABLED,
    style: '',
    onChange: undefined,
    onClick: undefined,
  },
  {
    name: 'price',
    label: 'price per unit',
    placeholder: 'enter a suggested price...',
    FormComponent: TextInput,
    value: '',
    state: Constants.ENABLED,
    style: '',
    onChange: undefined,
    onClick: undefined,
  },
]
